const FETCH_POKEMON_INFO_REQUEST = 'FETCH_POKEMON_INFO_REQUEST'
const FETCH_INFORMATION_SUCCESS = 'FETCH_INFORMATION_SUCCESS'
const FETCH_INFORMATION_FAILURE = 'FETCH_INFORMATION_FAILURE'

const typesObject = {
  FETCH_POKEMON_INFO_REQUEST,
  FETCH_INFORMATION_SUCCESS,
  FETCH_INFORMATION_FAILURE,
}

export default typesObject
